name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: docker.docker-compose
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag docker-in-docker:latest
      
  build-checkin:
    runs-on: docker.docker-compose
    steps: 
    - name: push the Docker image
      run: |
           docker login ${DOCKER_REPO}
           docker tag docker-in-docker:latest ${DOCKER_REPO}/docker-in-docker:$(date +%d%m%y)
           docker push ${DOCKER_REPO}/docker-in-docker:$(date +%d%m%y)
